from . import patient
from . import appointment
from . import prescription
from . import sale_order
from . import sale_order_line
from . import picking
from . import account_move
from . import stock_move
from . import prescription_report
from . import account_payment